### ISSUE TITLE
The traditional Chinese translation

### ISSUE THREAD

**Issue by qazrfv1234** [developersu/ns-usbloader-mobile#5]
Hi,
I completed the translation as the attachment.

Many thanks!
Leo

[The Traditional Chinese lang-file for ns-usbloader mobile v0.2.zip](https://github.com/developersu/ns-usbloader-mobile/files/4987114/The.Traditional.Chinese.lang-file.for.ns-usbloader.mobile.v0.2.zip)

**Comment by developersu** [comment]
Thank you!

**Comment by developersu** [comment]
Added since v1.0
